### ISSUE TITLE
TypeError: make_requirement_preparer() got an unexpected keyword argument 'wheel_download_dir'

### ISSUE THREAD

**Issue by jbarth-ubhd** [ocr-d-modul-2-segmentierung/ocrd-pixelclassifier-segmentation#18]
2020-12-18 tried to compile ocrd_all after `git pull`:

```
. /beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/bin/activate && make -C ocrd_pc_segmentation deps
make[2]: Entering directory `/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/ocrd_pc_segmentation'
pip install pip-tools
Requirement already satisfied: pip-tools in /beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages (5.3.1)
Requirement already satisfied: six in /beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages (from pip-tools) (1.15.0)
Requirement already satisfied: click>=7 in /beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages (from pip-tools) (7.1.2)
Requirement already satisfied: pip>=20.0 in /beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages (from pip-tools) (20.3.3)
pip-compile --upgrade
Traceback (most recent call last):
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/piptools/scripts/compile.py", line 458, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/piptools/resolver.py", line 173, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/piptools/resolver.py", line 278, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/piptools/resolver.py", line 388, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 232, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 163, in resolve_reqs
    wheel_download_dir=self._wheel_download_dir,
TypeError: make_requirement_preparer() got an unexpected keyword argument 'wheel_download_dir'
make[2]: *** [requirements.txt] Error 1
make[2]: Leaving directory `/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/ocrd_pc_segmentation'
make[1]: *** [/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf2/bin/ocrd-pc-segmentation] Error 2
make[1]: Leaving directory `/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all'
make: *** [/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/bin/ocrd-pc-segmentation] Error 2
```

**Comment by jbarth-ubhd** [comment]
This is merely a minor bug - I'm not using pc-segmentation.

**Comment by kba** [comment]
You have `pip-tools 5.3.1` but only 5.4.0+ supports pip 20.3+. pip-tools should be installed with `-U` in the makefile, I'll make a PR.
